### ISSUE TITLE
File not Found Issue when displaying character

### ISSUE THREAD

**Issue by morredor** [Shadez/wowarmory#55]
Almost all worked fine, I search the char, the tool show me the correct result, but when I click in the char:

```
Error Encountered
```

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

I´m stuck now.

BTW, very good looking tool, looking forward to see any ideas on how to fix this. thks.

**Comment by overy** [comment]
need core patch ... and looking characters must loged into game, for save to DB ...

**Comment by morredor** [comment]
i actually did 2 patch files into the trinity core, and another bunch on SQL armory table. I logged my char, stayed for some time online, did .save, and still this problem.

**Comment by overy** [comment]
use debug mod, and look "what is bad" (in cache)

**Comment by morredor** [comment]
This is from the log 'armory/cache/_debug/'
Armory revision: 350
DB Version: armory_r348
Configuration values are:
ArmoryConfig['settings']['configVersion'] = 708201001
ArmoryConfig['settings']['useCache'] = false
ArmoryConfig['settings']['cache_lifetime'] = 86400
ArmoryConfig['settings']['minlevel'] = 10
ArmoryConfig['settings']['minGmLevelToShow'] = 3
ArmoryConfig['settings']['defaultLocale'] = en_gb
ArmoryConfig['settings']['useDebug'] = true
ArmoryConfig['settings']['logLevel'] = 2

Mulitrealm info:
Realm ID: 1, name: Heaven, type: trinity

**Comment by overy** [comment]
test search your character, and look to 'armory/cache/_debug/'

**Comment by morredor** [comment]
but, thats it, i searched, the correct result came up, the error keep comming and the log is empty like that.

**Comment by overy** [comment]
hm i dont know, you can read FAQ (http://getmangos.com/community/showthread.php?t=12096), or wait for Shadez
BTW: In _debug must have 2 files, first "maybe config" and second is error log...mabye you post only "config" log...second file have undefined format, open him in your text editor

**Comment by morredor** [comment]
I already posted there too :p
but anyway, thanks for answering my issue.
cheers

**Comment by Shadez** [comment]
That's odd. If character have some restrictions, debug log will be filled anyway. Check access rights to /cache/ folder (it must have full write access). Also, check `armory_character_stats` table in characters database:

SELECT 1 FROM `armory_character_stats` WHERE `guid`=XXX

If query will return empty result, look at your core.

**Comment by morredor** [comment]
thnks, found the possible problem, my armory db does not have 'armory_character_stats' table. So now I ask, what sql from the pack should I dump into the db ? I did some already.

**Comment by morredor** [comment]
nevermind my last post, I´ve been no sleep for some days working on this server :p.

ok, found the table in char DB, and its not empty, theres 3 entry there (exactly 3 chars logged in-game since i installed it)

**Comment by morredor** [comment]
ok, more info. in the char DB, 'armory_character_stas' is properly being filled, but 'armory_game_chart' remains empty. and I just gave acess 777 to all cache folder, subfolder and all files. still nothing :s

**Comment by morredor** [comment]
finally, the log started pouring something:
DEBUG [08-08-2010 18:13:11]: ArmoryDatabaseHandler::_query : unable to execute SQL query (REPLACE INTO `armory_realm_data` (`id`, `name`) VALUES (1, 'Heaven')). MySQL error: none

ERROR [08-08-2010 18:13:11]: Utils::CheckConfigRealmData : realm data for realm "Heaven" was not added to `armory_realm_data` table. Please, execute this query manually: "REPLACE INTO `armory_realm_data` (`id`, `name`) VALUES (1, 'Heaven');"

DEBUG [08-08-2010 18:13:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `last_login` FROM `account` WHERE `id`=5). MySQL error: none

**Comment by morredor** [comment]
sorry for the flooding, but I believe this could be good for futere users with the same error.

So now I fixed the previous problem, I manually had to add some info on the armory_realm_data table, so now I no longer get the error page, and the proper char page is now shown.

but still :
ERROR [08-08-2010 19:00:12]: Items::GetItemModelData : unable to get model data for displayID 12684 (row: visual_1, itemid: 6139)
and a new problem, now the loading bar for the char view does not complete, even itemless chars :p

but anyway, thanks for helping, driving me to the right direction to solve this, and for developing this very good looking tool.
ps: this problem was solved, and this thread can be closed.
cheers

**Comment by ralnick** [comment]
@ Morredor  I am getting the same error.. can you explain how you fixed the error with a little more detail?? Also, I know I have to patch the core with the patch file.. but how does one go about doing that?? TIA

**Comment by morredor** [comment]
lucky you, caught me online :p

Ok, I solved the problem by manually inserting the proper data into armory_realm_data table on SQL. Check this table in your SQL, if its empty (mine was), create 1 entry with the apropriate data for each realm you have (you will know when you get there :p). 
cheers

**Comment by ralnick** [comment]
ok.... changed the 333 to 335 as I am guessing that is what i needed to change everything else looks right realm ID 1 .. Name  version # ..... so that was done.... but still nothing.. I get the same error... I must be still missing the core patch.... any help on this would be great.... and thanks for replying to my first post. how do I apply the patch.... Been doing alot of searching for this answer.. but nothing.... please help. TIA

**Comment by morredor** [comment]
If you already didnt, you have to patch the core with the files on 'tools/trinity_core folder' folder (im assuming you are using trinity). In this folder, theres a SQL file (also need to be patched) and 2 core patch files. You can either use tortoise and patch them automatically, or you can do it manually (in this case you have to open the .patch files in a simple notepad and do the 'copy-and-paste' method in your core).
cheers
